config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # resources :realms
  # resources :statuses
  # resources :comments
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  scope '(:locale)', locale: /en|mi/ do
    resources :pitches do
      get 'convert'
      resources :creatives
    end
    resources :ideas do
      member do
        post 'toggle_bookmark', to: 'ideas#toggle_bookmark'
      end
      resources :comments
      resources :ratings
    end
    resources :ratings
    resources :briefs, only: [:index, :show]
    get 'leaderboards', to: 'leaderboards#show'
    get ':page' => 'static#show'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'ideas#index'
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user, inverse_of: :pitches
  belongs_to :idea
  has_many :creatives
  has_many :core_creatives, through: :creatives, source: :users
  belongs_to :brief

  validates_presence_of :title, :logline, :synopsis, :brief
  
  accepts_nested_attributes_for :creatives, allow_destroy: true

  has_paper_trail
  
  # https://medium.com/@ryanwerner_57863/how-to-build-a-nested-form-in-rails-using-fields-for-c185210f6869
  def creatives_attributes=(creatives_attributes)
    creatives_attributes.each do |i, creative_attribute|
      self.creatives.build(creative_attribute)
    end
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: %i[ show edit update destroy ]

  # GET /pitches or /pitches.json
  def index
    @pitches = Pitch.all
  end

  # GET /pitches/1 or /pitches/1.json
  def show
    # this doesn't work because the view tries to list the new creative, and comes up empty
    # @new_creative = @pitch.creatives.build
  end

  # GET /pitches/new
  def new
    @pitch = Pitch.new
    # @pitch = current_user.pitches.build
  end

  # GET /pitches/1/edit
  def edit
  end

  # POST /pitches or /pitches.json
  def create
    logger.warn "\n\nCurrent User: #{current_user.inspect}\n\n"
    # @pitch = Pitch.new(pitch_params)
    @pitch = current_user.pitches.build(pitch_params)
    # @pitch.core_creatives.build({user: current_user, position: "mung"})
    logger.warn "\n\nPitch: #{@pitch.inspect}"
    logger.warn "\n\nCore Creatives: #{@pitch.creatives.inspect}\n\n"

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to pitch_url(@pitch), notice: "Pitch was successfully created." }
        format.json { render :show, status: :created, location: @pitch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitches/1 or /pitches/1.json
  def update
    logger.warn("CURRENT USER: " + current_user.inspect)
    respond_to do |format|
      if @pitch.update(pitch_params)
        format.html { redirect_to pitch_url(@pitch), notice: "Pitch was successfully updated." }
        format.json { render :show, status: :ok, location: @pitch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitches/1 or /pitches/1.json
  def destroy
    @pitch.destroy

    respond_to do |format|
      format.html { redirect_to pitches_url, notice: "Pitch was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def convert
    logger.warn "CONVERT!! #{params}"
    @pitch = Pitch.new
    @pitch.user = current_user
    @pitch.idea = Idea.find(params[:pitch_id])
    @pitch.title = @pitch.idea.title
    @pitch.synopsis = @pitch.idea.content
    @pitch.creatives.build
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pitch_params
      params.require(:pitch).permit(:synopsis, :slides, :presentation_datetime, :user_id, :title, :tagline, :logline, :idea_id, :brief_id, creatives_attributes: [:pitch_id, :user_id, :position])
    end
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/views/pitches/_card.html.erb
<div class="col">
  <div class="card h-100" data-controller="idea">
  	<div class="card-header d-flex" style="height: 100px;">
    	<h5 class="me-auto"><%= truncate(pitch.title, length:60) %></h5>
  	</div>
  	<div class="card-body">
			<p class="card-text text-left" style="height: 100px;">
				<%= truncate(pitch.tagline, length: 80) %>
			</p>
		</div>
		<div class="card-footer text-muted d-grid gap-2">
			<div class="hstack gap-3">
				<%= link_to "More…", pitch, class: "btn btn-outline-primary btn-sm w-75" %>
			</div>
			<small>Created by: <%= pitch.user.full_name() %> on <%= pitch.created_at.strftime("%d/%m/%Y") %></small>
		</div>
  </div>
</div>

app/views/pitches/_form.html.erb
<%= form_with(model: pitch) do |form| %>
  <% if pitch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pitch.errors.count, "error") %> prohibited this pitch from being saved:</h2>

      <ul>
        <% pitch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label :title, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :tagline, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :tagline, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :logline, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :logline, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :synopsis, class: "col-sm-2 col-form-label col-form-label-sm",  id: "myEditor" %>
    <div class="col-sm-10">
      <%= form.text_area :synopsis, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="d-grid">
    <%= form.submit "Submit", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/pitches/_pitch.html.erb
<div class="card my-2">
  <div class="card-header">
    <h1 class="display-1"><%= pitch.title %></h1>
    <h2><%= pitch.tagline %></h2>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-12 col-lg-6">
        <h3>Logline</h3>
        <p class="lead">
          <%= pitch.logline %>
        </p>
        
        <h3>Brief</h3>
        <p class="lead">
          <%= pitch.brief.title %>
        </p>
        
        <h3>Synopsis</h3>
        <p style="white-space: pre-line;">
          <%= pitch.synopsis %>
        </p>
      </div>
      <div class="col-12 col-lg-6">
        <h3>Core Creatives</h3>
          <ul class="list-group">
            <%# render partial: "creative", collection: pitch.core_creatives, as: :creative %>
            <%= render pitch.creatives %>
          </ul>
          <em>The ability to add further core creatives will be added at a later date.</em>
          <%= turbo_frame_tag "new_creative", src: new_pitch_creative_path(pitch) %>
          <%# turbo_frame_tag "new_comment", src: idea_comment_path(@idea), target: "_top" %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <small>Created by: <%= pitch.user.full_name() %> on <%= pitch.created_at.strftime("%d/%m/%Y") %> • <%= link_to 'View original idea', pitch.idea %></small>
  </div>
</div>

app/views/pitches/convert.html.erb
<h1>Convert Idea</h1>

<%= form_with(model: @pitch) do |form| %>
  <% if @pitch.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@pitch.errors.count, "error") %> prohibited this pitch from being saved:</h2>

      <ul>
        <% @pitch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label :title, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :tagline, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :tagline, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :logline, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :logline, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :synopsis, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_area :synopsis, class: "form-control form-control-lg" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= form.label :brief, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.collection_select :brief_id, Brief.order(:title), :id, :title, {prompt: false}, {class: "form-select form-select-sm"} %>
    </div>
  </div>

  <div>
    <%= form.hidden_field :idea_id, value: @pitch.idea_id %>
    <%= form.hidden_field :user_id, value: @pitch.user_id %>
  </div>
  <%= form.fields_for :creatives do |creatives_subform| %>
  <div class="row mb-3">
    <%= creatives_subform.label 'What is your role on this project?', class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= creatives_subform.hidden_field :user_id, value: @pitch.user_id %>
      <%= creatives_subform.text_field :position, class: "form-control form-control-lg" %>
    </div>
  </div>
  <% end %>

  <div class="d-grid">
    <%= form.submit "Submit", class: "btn btn-large btn-primary" %>
  </div>
  <div class="d-grid my-2">
    <%= link_to "Cancel", idea_path(@pitch.idea), class: "btn btn-large btn-danger" %>
  </div>
<% end %>

app/views/pitches/creative.turbo_stream.erb
<turbo-stream action="append" target="creatives">
  <template>
    <li class="list-group-item">
      <%= creative.user.full_name %>, <%= creative.position %>
    </li>
  </template>
</turbo-stream>

app/views/pitches/edit.html.erb
<h1>Editing pitch</h1>

<%= render "form", pitch: @pitch %>

<div class="d-grid my-2">
  <%= link_to "Cancel", pitch_path(@pitch), class: "btn btn-large btn-danger" %>
</div>

app/views/pitches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pitches</h1>

<div id="pitches">
  <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-3 g-4">
      <%= render partial: "card", collection: @pitches, as: :pitch %>
  </div>
</div>

app/views/pitches/new.html.erb
<h1>Convert Idea</h1>

<%= render "form", pitch: @pitch %>

<br>

<div>
  <%= link_to "Back to pitches", pitches_path %>
</div>

app/views/pitches/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-grid gap-2 mt-3">
  <%= link_to "Back to pitches", pitches_path, class: "btn btn-outline-primary btn-lg" %>
</div>

<%= render @pitch %>

<% if current_user == @pitch.user %>
<div class="hstack gap-2 mx-auto my-2">
  <%= link_to "Edit", edit_pitch_path(@pitch), class: "btn btn-warning btn-lg w-100" %>
  <%= button_to "Delete", @pitch, method: :delete, class: "btn btn-danger btn-lg w-100" %>
</div>
<% end %>