config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # resources :realms
  # resources :statuses
  # resources :comments
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  scope '(:locale)', locale: /en|mi/ do
    resources :pitches do
      get 'convert'
      resources :creatives
    end
    resources :ideas do
      member do
        post 'toggle_bookmark', to: 'ideas#toggle_bookmark'
      end
      resources :comments
      resources :ratings
    end
    resources :ratings
    resources :briefs, only: [:index, :show]
    get 'leaderboards', to: 'leaderboards#show'
    get ':page' => 'static#show'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'ideas#index'
end

app/models/brief.rb
class Brief < ApplicationRecord
  has_one :pitch
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  before_action :set_brief, only: %i[show]
  
  def index
    @briefs = Brief.all
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_brief
    @brief = Brief.find(params[:id])
  end
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/views/briefs/_card.html.erb
<div class="col">
  <div class="card h-100" data-controller="idea">
    <div class="card-header d-flex" style="height: 100px;">
      <h5 class="me-auto"><%= brief.title %></h5>
    </div>
    <div class="card-body">
      <p class="card-text text-left" style="height: 60px;">
        <%= brief.tagline %>
      </p>
    </div>
    <div class="card-footer text-muted d-grid gap-2">
      <div class="hstack gap-3">
        <%= link_to "More…", brief, class: "btn btn-outline-primary btn-sm w-75" %>
      </div>
    </div>
  </div>
</div>

app/views/briefs/index.html.erb
  <div class="row row-cols-1 row-cols-sm-2 row-cols-xl-3 g-4">
    <%= render partial: "card", collection: @briefs, as: :brief %>
  </div>

app/views/briefs/show.html.erb
<div>
  <div class="d-grid gap-2 mt-3">
    <%= link_to "Back to briefs", briefs_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
  <div class="card my-2">
    <div class="card-header">
      <h1 class="display-1"><%= @brief.title %></h1>
      <h2><%= @brief.tagline %></h2>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-12 col-lg-6">          
          <h3>Introduction</h3>
          <p style="white-space: pre-line;">
            <%= @brief.overview %>
          </p>
        </div>
        <div class="col-12 col-lg-6">          
          <h5>Core Deliverable</h5>
          <p style="white-space: pre-line;">
            <%= @brief.core_deliverable -%>
          </p>
          <h5>Supplementary Deliverable</h5>
          <p style="white-space: pre-line;">
            <%= @brief.supplementary_deliverable -%>
          </p>
        </div>
      </div>
    </div>
    <div class="card-footer">
      
    </div>
  </div>
</div>