config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # resources :realms
  # resources :statuses
  # resources :comments
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  scope '(:locale)', locale: /en|mi/ do
    resources :pitches do
      get 'convert'
      resources :creatives
    end
    resources :ideas do
      member do
        post 'toggle_bookmark', to: 'ideas#toggle_bookmark'
      end
      resources :comments
      resources :ratings
    end
    resources :ratings
    resources :briefs, only: [:index, :show]
    get 'leaderboards', to: 'leaderboards#show'
    get ':page' => 'static#show'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'ideas#index'
end

app/models/creative.rb
class Creative < ApplicationRecord
  belongs_to :user
  belongs_to :pitch
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  before_action :set_creative, only: %i[ show edit update destroy ]

  # GET /creatives or /creatives.json
  def index
    @creatives = Creative.all
  end

  # GET /creatives/1 or /creatives/1.json
  def show
  end

  # GET /creatives/new
  def new
    @creative = Creative.new
  end

  # GET /creatives/1/edit
  def edit
  end

  # POST /creatives or /creatives.json
  def create
    @creative = Creative.new(creative_params)

    respond_to do |format|
      if @creative.save
        format.html { redirect_to creative_url(@creative), notice: "Creative was successfully created." }
        format.json { render :show, status: :created, location: @creative }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatives/1 or /creatives/1.json
  def update
    respond_to do |format|
      if @creative.update(creative_params)
        format.html { redirect_to creative_url(@creative), notice: "Creative was successfully updated." }
        format.json { render :show, status: :ok, location: @creative }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatives/1 or /creatives/1.json
  def destroy
    @creative.destroy

    respond_to do |format|
      format.html { redirect_to creatives_url, notice: "Creative was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creative
      @creative = Creative.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creative_params
      params.require(:creative).permit(:position, :user_id, :pitch_id)
    end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_creative.html.erb
<li class="list-group-item d-flex" id="<%= dom_id creative %>">
  <div class="me-auto">
    <%= creative.user.full_name %>
  </div>
  <div class="text-secondary">
    <%= creative.position %>
  </div>
</li>

app/views/creatives/_form.html.erb
<%= turbo_frame_tag "new_creative" %>
  <%= form_with(model: [@creative.pitch, @creative]) do |form| %>
    <% if creative.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(creative.errors.count, "error") %> prohibited this creative from being saved:</h2>
  
        <ul>
          <% creative.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :position, style: "display: block" %>
      <%= form.text_field :position %>
    </div>
  
    <div>
      <%= form.label :user_id, style: "display: block" %>
      <%= form.text_field :user_id %>
    </div>
  
    <div>
      <%= form.label :pitch_id, style: "display: block" %>
      <%= form.text_field :pitch_id %>
    </div>
  
    <div class="d-grid">
      <%= form.submit "Submit", class: "btn btn-large btn-primary" %>
    </div>
  <% end %>
<%# end %>

app/views/creatives/edit.html.erb
<h1>Editing creative</h1>

<%= render "form", creative: @creative %>

<br>

<div>
  <%= link_to "Show this creative", @creative %> |
  <%= link_to "Back to creatives", creatives_path %>
</div>

app/views/creatives/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Creatives</h1>

<div id="creatives">
  <% @creatives.each do |creative| %>
    <%= render creative %>
    <p>
      <%= link_to "Show this creative", creative %>
    </p>
  <% end %>
</div>

<%= link_to "New creative", new_creative_path %>

app/views/creatives/new.html.erb
<h1>New creative</h1>

<%= render "form", creative: @creative %>

<br>

<div>
  <%= link_to "Back to creatives", creatives_path %>
</div>

app/views/creatives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @creative %>

<div>
  <%= link_to "Edit this creative", edit_creative_path(@creative) %> |
  <%= link_to "Back to creatives", creatives_path %>

  <%= button_to "Destroy this creative", @creative, method: :delete %>
</div>